version: "3.8"

services:
  app:
    build: ./docker
    container_name: app
    command: wait-for db:3306 -t 40 -- ./docker/start.sh
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - .:/home/php/app
    depends_on:
      - db
    networks:
      - network-app

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=mypassword
    volumes:
      - ./_dbData:/var/lib/mysql
    networks:
      - network-app

networks:
  network-app:
    driver: bridge
